version: "3.5"

services:
  nestjs:
    build:
      context: ./packages/nestjs
      dockerfile: Dockerfile.dev
    env_file:
     - ./packages/nestjs/.env.dev
    ports:
      - 3001:3001
    volumes:
      - ./packages/nestjs/:/app
      - /app/node_modules

  react_app:
    build:
      context: ./packages/react-app
      dockerfile: Dockerfile.dev
    env_file:
     - ./packages/react-app/.env.dev
    ports:
      - 3000:3000
    volumes:
      - ./packages/react-app/:/app
      - /app/node_modules

  mysql:
    image: mysql
    command: 
      - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes: 
      - ./init_db.sh:/data/application/init_db.sh
      # - "./mysql:/var/lib/mysql"
      #- "./init.sql:/docker-entrypoint-initdb.d"
    ports:
     - 3306:3306 

      # links:
      # - "mongo:mongo.openconceptlab.org"
      # - "solr:solr.openconceptlab.org"
      # - "some-service:some-alias"